sudo: required
dist: xenial
os: linux
language: minimal
addons:
  apt:
    packages:
    - qt5-default
    - qt5-qmake
    - qtbase5-dev-tools
    - qttools5-dev-tools
    - build-essential
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-thread-dev
    - libssl-dev
    - libdb++-dev
    - libminiupnpc-dev
    - libqrencode-dev
env:
  global:

before_install:
install:
before_script:
    - mkdir -p src/obj/zerocoin
    - mkdir -p build

script:
#build daemon
    - cd src
    - make "STATIC=1" -B -w -f makefile.unix -j3
    - cd ..

#build gui wallet
    - cd build
    - qmake ..
    - make -j3
    - cd ..

after_script:
    - echo "Done"
