sudo: required
dist: xenial
osx_image: xcode9.4
os:
- osx
- linux
language: cpp
cache:
- ccache
- directories:
    - $HOME/Library/Caches/Homebrew
env:
  global:
    CCACHE_MAXSIZE: 1G
    secure: hi4pDxnjHCeb75FeQUjMQCdE+UwCOO6CqOnkFTGLM8uroBcs9YChW2UJUKqMwEeK+s0kCBDe5GvlFc3joDclX/aEMTBvOECUd8L8Y8+tEknZaNvk7Xl+EI+Rror33gnr4XYpJ4qQbubkM/aMnH5fYJFA6lCDbD/mztizw9Gc1kWZc6+px7liifUOmPrL5CuF9S5tgB7C2erZoZG0pxPSWx16yKyTzDzoMVIUjwubeDf7luMrTT8mkaMFl0ZLq5/+joEMBDjtRMCfS0ap9YnAbbcoY5xpelAZYY5c+6LjUIKng+r8hUtHabCBoFdcboRpeBymG5TUufBjr3lChxfnnVsch02Zu+r0CLkpd9P0oGpohUXn5iZRfSSo/Rb2t2swIZp4Cd8uabie0l0BVL8yTf/bvv6LWZ7BZQsrj22z+dxwIJGCDlsKS4zqmvlSsXzSOIZMLvrfTRUtYlQzC2tLs9UrPzgCS6PzQixmUk4vK3u6m9+i5eI7B6rDzkkEnDgfyr04aI2EE5zakzUYl/mOKYQHCDbq0xE+s29rzTGytA0qq06Fw4HNF1HOxv+27bPAQxBnlo5XCVb+v7XEVHP+dmjkzcx5DusbqkCctCOnyLYMMobPLnRI64XCpfF7zHUkonwYkag8vObf2D3jCxijAvVW3IpvcXbdkH7NXzQxW1A=
  matrix:
  - target_v=osx
  - target_v=osx_test
  - target_v=rpi_daemon_wallet
  - target_v=linux_wallet_test
  - target_v=linux_wallet
  - target_v=windows
  - target_v=linux_daemon
matrix:
  exclude:
  - os: osx
    env: target_v=windows
  - os: osx
    env: target_v=linux_daemon
  - os: osx
    env: target_v=linux_wallet
  - os: osx
    env: target_v=linux_wallet_test
  - os: osx
    env: target_v=rpi_daemon_wallet
  - os: linux
    env: target_v=osx
  - os: linux
    env: target_v=osx_test
before_install:
install:
before_script:
script:
- if [[ "$target_v" == "osx"               ]]; then python ci_scripts/test_osx-gui_wallet.py        ; fi
- if [[ "$target_v" == "osx_test"          ]]; then python ci_scripts/test_osx-gui_wallet.py -t     ; fi
- if [[ "$target_v" == "rpi_daemon_wallet" ]]; then python ci_scripts/test_rpi-daemon-gui.py        ; fi
- if [[ "$target_v" == "linux_wallet_test" ]]; then python ci_scripts/test_linux-gui_wallet.py -t   ; fi
- if [[ "$target_v" == "linux_wallet"      ]]; then python ci_scripts/test_linux-gui_wallet.py      ; fi
- if [[ "$target_v" == "windows"           ]]; then python ci_scripts/test_win32-gui_wallet.py      ; fi
- if [[ "$target_v" == "linux_daemon"      ]]; then python ci_scripts/test_linux-daemon.py          ; fi

after_script:
- echo "Done"
notifications:
  email:
    recipients:
    - info@nebl.io
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  - provider: s3
    endpoint: https://ams3.digitaloceanspaces.com
    access_key_id: 2VUF47CKX6AGTOKSGPBC
    secret_access_key:
      secure: DgrrcxBrf2mgfWN30ACSIgEhQJaIaWuJKO3/gAQR/1la434O5U+hnJ0nFzF431eogeBXwV5gdcsuIQaxcg2pB40orrQ1QEnwL8CQZfB0A9dyAr0YRFS9aWg4vF2UjvYkLF1iFaRjjpdxjLtdamlXG5Ea7jsxn4vLNRQm09SYoBLVXn7JYiLvyVsrtpaVR0E/hCl+U7rQVtkVSI5d0jUKUQimV7cgYhYGUsDnOQZcGdXHhQp7Hv0IQ8KSLdmH6At0DQiAmr6p0z6ToEn0uq2iZip6pPcz/VrnbUIPV8zJjlyyZ9I9MQ8h+V33iSeHCgOGXqIRH6E5IR3yfWUfvk6qUt3vVxU+wI0avceOC1wrV8qTqr6CJ8rvTnCMzHTuDtBK4lyNYregz+3Omj7zIKEiHt3lsyM1ClJixD0xJVuxNr2CRxgK4A53eHvRhZ+wjAPseVT06tfs3JaR0wxuO1QB5Xp4BUUwQF9jGnUu2GazIbJVkhFQMFmuwTDk8kwpVaQmVlkOMuYkThpxOf3vSMztKvtZ8lImFh7Ci8leQ8TQOxloZLPJwIvYadILjatX2k7btAKTkCawQSdmOZJh22c8M1aYxR/TxcnEyah43FhMyRQ/LNdWkvsWHFwpHHryLD8sEuZy2liotFFIgqfiaAFTF94Sm6F29DhHglh1SdGEznM=
    bucket: neblio-build-staging
    skip_cleanup: true
    detect_encoding: true
    local_dir: deploy
    acl: public_read
    overwrite: true
    on:
      repo: NeblioTeam/neblio
      all_branches: true
  - provider: releases
    api_key:
      secure: h0Cgy4kPdBLSnIrBSeAqAqFVBmblD21+UPLn/NeyL3CRODjWmwggE9il6b3Y8aPhkKwfQmCuzjO4ZAHK8tRc+F/jncdu8xEc4L6r7OEoPESujqOqWcFikj2RoU9IThNyzvwfXqDJ9IHHn0bvsl//Npro0llBjltpe2bODhqhKEwTEt79XgQ+v9S/QRM6lkO1CAPXPS/2iVBqSQfMytP70ZK9WnZ5M1yjS4msysbGOAS00hfwewyqU6KxzSRDnUGpTet6fStMCNxjO2xJaSqyFMKG/ROSk6InGDOKomcIEF4KWG4i5iyl/m63/1F4/mlyupvGhitf5hYcQHZW/23Fddec3cBYb4oSLB+uVHyuxm1c5BqyJsUD/MuWOFgIfRb2UIfko2EOS8rMDUZUGlJYPTjsoqWbqnAJEb3cBdT2WP8bYjxn+65T7KK4ysP+1U63KSG7Dn/+NJZxQXZRl74JjRDhueFrDsgbQMo1M1cC14WpUZIC2FZQ8y+b9BggMb+VLOOWwxzG+y24vcntTVWyFvfHBhSY2yfJnvMGvO6E1isFnIG60MOTJd63PX5jkKN/AhIDneh1lCGx+3i0LzyHuddh8mP6d5ZJsEbvHBFk54Rv76I0MUKiJXKc1Mmxzm48heptK9pL5/xvxrmo+LoKjONG+w9A2NcgzoSqOqFxuHE=
    file_glob: true
    file: deploy/*---neblio*
    skip_cleanup: true
    prerelease: true
    on:
      repo: NeblioTeam/neblio
      all_branches: true
      tags: true
