sudo: required
dist: trusty
os:
    - linux
    - os
language: minimal
env:
  global:

before_install:
install:
before_script:
script:
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python ci_scripts/test_linux-gui_wallet.py    ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python ci_scripts/test_linux-daemon_wallet.py ; fi

#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then x86_64-apple-darwin11 ; fi
    - x86_64-apple-darwin11 --help

after_script:
    - echo "Done"
