sudo: required
dist: trusty
os:
    - linux
    - os
language: minimal
env:
  global:
  matrix:
    - os_v=win
    - os_v=linux
before_install:
install:
before_script:
script:
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python ci_scripts/test_linux-gui_wallet.py    ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python ci_scripts/test_linux-daemon_wallet.py ; fi

#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then x86_64-apple-darwin11 ; fi
    - echo $os_v

after_script:
    - echo "Done"
