sudo: required
dist: xenial
osx_image: xcode8.3
os:
    - linux
    - osx
language: minimal
env:
  global:
  matrix:
    - target_v=windows
    - target_v=linux_daemon
    - target_v=linux_wallet
    - target_v=linux_wallet_test
    - target_v=osx
    - target_v=osx_test
matrix:
  exclude:
    - os: osx
      env: target_v=windows
    - os: osx
      env: target_v=linux_daemon
    - os: osx
      env: target_v=linux_wallet
    - os: osx
      env: target_v=linux_wallet_test
    - os: linux
      env: target_v=osx
    - os: linux
      env: target_v=osx_test
before_install:
install:
before_script:
script:
    - if [[ "$target_v" == "windows"           ]]; then python ci_scripts/test_win32-gui_wallet.py     ; fi
    - if [[ "$target_v" == "linux_daemon"      ]]; then python ci_scripts/test_linux-daemon.py         ; fi
    - if [[ "$target_v" == "linux_wallet"      ]]; then python ci_scripts/test_linux-gui_wallet.py     ; fi
    - if [[ "$target_v" == "linux_wallet_test" ]]; then python ci_scripts/test_linux-gui_wallet.py -t  ; fi
    - if [[ "$target_v" == "osx"               ]]; then python ci_scripts/test_osx-gui_wallet.py       ; fi
    - if [[ "$target_v" == "osx_test"          ]]; then python ci_scripts/test_osx-gui_wallet.py -t    ; fi


after_script:
    - echo "Done"

notifications:
  email:
    recipients:
      - info@nebl.io
