sudo: required
dist: trusty
os: linux
language: minimal
addons:
  apt:
    packages:
    - qt5-default
    - qt5-qmake
    - qtbase5-dev-tools
    - qttools5-dev-tools
    - build-essential
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-thread-dev
    - libssl-dev
    - libdb++-dev
    - libminiupnpc-dev
    - libqrencode-dev
env:
  global:

before_install:
install:
before_script:
    - mkdir build
    - cd build

script:
    - qmake ..
    - make

after_script:
    - echo "Done"
