name: CI CD
on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux_daemon:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: ccache
      uses: actions/cache@v1
      with:
        path: .ccache
        key: ${{ runner.OS }}--linux_daemon-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}--linux_daemon-
    - name: Build nebliod for Linux
      run: |
        python -u ci_scripts/test_linux-daemon.py
  linux_wallet:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: ccache
      uses: actions/cache@v1
      with:
        path: .ccache
        key: ${{ runner.OS }}--linux_wallet-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}--linux_wallet-
    - name: Build neblio-Qt for Linux
      run: |
        python -u ci_scripts/test_linux-gui_wallet.py
  windows_x86:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: ccache
      uses: actions/cache@v1
      with:
        path: .ccache
        key: ${{ runner.OS }}--windows_x86-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}--windows_x86-
    - name: Build neblio-Qt for Windows x86
      run: |
        python -u ci_scripts/test_win_x86-gui_wallet.py
